# Generated by Django 5.0.2 on 2024-02-12 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profilemodel_created_alter_profilemodel_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='slug',
        ),
    ]
