# Generated by Django 5.0.2 on 2024-02-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_profilemodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
