# Generated by Django 5.0.2 on 2024-02-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profilemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='main/img/profile'),
        ),
    ]
