# Generated by Django 5.0.2 on 2024-02-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_profilemodel_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='creator',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
